//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotRDb.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public int ActorId { get; set; }
        public int NodeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Node Node { get; set; }
    }
}
