//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotRDb.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public int DatumId { get; set; }
        public Nullable<int> NodeId { get; set; }
        public Nullable<int> EdgeId { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> QuantityType { get; set; }
        public Nullable<int> DatumType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
    
        public virtual Edge Edge { get; set; }
        public virtual Node Node { get; set; }
    }
}
