//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotRDb.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdgeType
    {
        public EdgeType()
        {
            this.Edges = new HashSet<Edge>();
        }
    
        public int EdgeTypeId { get; set; }
        public string TypeName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> FromType { get; set; }
        public Nullable<int> ToType { get; set; }
    
        public virtual ICollection<Edge> Edges { get; set; }
    }
}
