//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotRDb.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edge
    {
        public Edge()
        {
            this.Data = new HashSet<Datum>();
        }
    
        public int EdgeId { get; set; }
        public int EdgeTypeId { get; set; }
        public int FromNodeId { get; set; }
        public int ToNodeId { get; set; }
        public Nullable<int> HyperedgeId { get; set; }
    
        public virtual EdgeType EdgeType { get; set; }
        public virtual Node From { get; set; }
        public virtual Node To { get; set; }
        public virtual ICollection<Datum> Data { get; set; }
    }
}
