//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotRDb.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeType
    {
        public NodeType()
        {
            this.Nodes = new HashSet<Node>();
        }
    
        public int NodeTypeId { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Node> Nodes { get; set; }
    }
}
