//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotRDb.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityType
    {
        public QuantityType()
        {
            this.Data = new HashSet<Datum>();
        }
    
        public int QuantityTypeId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<Datum> Data { get; set; }
    }
}
