//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotRDb.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dotRDbEntities : DbContext
    {
        public dotRDbEntities()
            : base("name=dotRDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actor> Actors { get; set; }
        public DbSet<Edge> Edges { get; set; }
        public DbSet<EdgeType> EdgeTypes { get; set; }
        public DbSet<Node> Nodes { get; set; }
        public DbSet<NodeType> NodeTypes { get; set; }
        public DbSet<Process> Processes { get; set; }
        public DbSet<QuantityType> QuantityTypes { get; set; }
        public DbSet<Resource> Resources { get; set; }
        public DbSet<Datum> Data { get; set; }
        public DbSet<DatumType> DatumTypes { get; set; }
    }
}
